name: Build & Push Docker Image

on:
  push:
    branches:
      - master

env:
  APP_NAME: bfcdevme
  OWNER: pakistanesss
  DOCKER_FILE_PATH: BFC.Dev.Web

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - uses: actions/checkout@v3

      # 2️⃣ Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN || github.token }}

      # 3️⃣ Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/$OWNER/$APP_NAME:latest -f $DOCKER_FILE_PATH/Dockerfile .

      # 4️⃣ Push Docker image
      - name: Push Docker Image
        run: |
          docker push ghcr.io/$OWNER/$APP_NAME:latest
